apiVersion: apps/v1
kind: Deployment
metadata:
  name: fnn-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fnn-inference
  template:
    metadata:
      labels:
        app: fnn-inference
    spec:
      containers:
        - name: inference
          image: fnn-inference:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: KAFKA_BROKER
              value: "kafka-svc:9092"
          volumeMounts:
            - name: shared-data
              mountPath: /data
      volumes:
        - name: shared-data
          hostPath:
            path: /data
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: fnn-inference-svc
spec:
  type: NodePort
  selector:
    app: fnn-inference
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
